[package]
name = "merino-adm"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.2.4"
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_qs = "0.8.3"
serde_with = "1.9"
remote-settings-client = { git = "https://github.com/mozilla-services/remote-settings-client", rev = "a489fa2ac9aca128d06eb35dd435f24b7ff9c8f8" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
anyhow = "1.0.40"
reqwest = { version = "0.11.3", features = ["json"] }
tokio = { version = "1.5.0", features = ["rt", "macros", "rt-multi-thread"] }
radix_trie = "0.2.1"
merino-suggest = { path = "../merino-suggest" }
futures = "0.3.14"
merino-settings = { path = "../merino-settings" }
tracing = "0.1.26"
lazy_static = "1.4.0"
async-trait = "0.1"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.7.1"
actix-rt = "2.2"
[package]
name = "merino-cache"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "^1"
async-trait = "^0.1"
merino-settings = { path = "../merino-settings" }
merino-suggest = { path = "../merino-suggest" }
redis = { version = "^0.20", features = ["tokio-comp", "connection-manager"] }
tokio = "^1"
tracing = "^0.1"
serde = "^1"
serde_json = "^1"
tracing-futures = "^0.2"

[dev-dependencies]
proptest = "^1"
http = "^0.2"
# A fake top-level package for documentation. No code should go here, and most
# documentation should be in the specific packages above.
[package]
name = "merino"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-rt = "2.2.0"
anyhow = "1.0.40"
merino-web = { path = "../merino-web" }
merino-settings = { path = "../merino-settings" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
tracing-subscriber = { version = "0.2.18", features = ["registry", "env-filter"] }
tracing = "0.1.26"
tracing-log = "0.1.2"
tracing-actix-web-mozlog = "0.2"
[package]
name = "merino-integration-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-rt = "2.2.0"
tokio = "1.5.0"
tokio-test = "0.4.1"
reqwest = { version = "0.11.3", features = ["json"] }
anyhow = "1.0.40"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
serde_with = "1.8.1"
merino-web = { path = "../merino-web" }
merino-settings = { path = "../merino-settings" }
httpmock = "0.5.8"
viaduct = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
tracing-futures = "0.2"
maplit = "1.0.2"
lazy_static = "^1.4.0"
redis = "^0.20"
deadpool = "^0.8"
[package]
name = "merino-settings"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
config = "0.11.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_with = "1.9"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.18", features = ["env-filter"] }
http = "0.2"
serde_path_to_error = "0.1.4"
redis = "^0.20"
[package]
name = "merino-suggest"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.2.4"
serde = { version = "1.0.125", features = ["derive"] }
serde_with = "1.9.1"
async-trait = "0.1"
merino-settings = { path = "../merino-settings" }
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
serde_json = "1.0"
[package]
name = "merino-web"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "=4.0.0-beta.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
actix-cors = "0.6.0-beta.1"
tokio = { version = "1.5.0", features = ["sync"] }
anyhow = "1.0.40"
merino-suggest = { path = "../merino-suggest" }
merino-adm = { path = "../merino-adm" }
merino-cache = { path = "../merino-cache" }
merino-settings = { path = "../merino-settings" }
uuid = { version = "0.8.2", features = ["v4"] }
tracing = { version = "0.1.26", features = ["async-await"] }
tokio-test = "0.4.1"
tracing-actix-web-mozlog = "0.2"
futures-util = "0.3"
tracing-futures = "0.2"

[dev-dependencies]
actix-rt = "2.2.0"
