[package]
name = "merino-adm"
version = "0.1.0"
authors = ["Michael Cooper <mythmon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_qs = "0.8.3"
serde_url_params = "0.2.1"

[dev-dependencies]
pretty_assertions = "0.7.1"
