[package]
name = "merino-adm"
version = "0.1.0"
authors = ["Michael Cooper <mythmon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "=4.0.0-beta.5"
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_qs = "0.8.3"
serde_url_params = "0.2.1"
remote-settings-client = { git = "https://github.com/mozilla-services/remote-settings-client", rev = "06fbe92e3e45c42ff1bdd9b71ceda6e9e908a656" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
anyhow = "1.0.40"
env_logger = "0.8.3"
reqwest = { version = "0.11.3", features = ["json"] }
tokio = { version = "1.5.0", features = ["rt", "macros", "rt-multi-thread"] }
radix_trie = "0.2.1"
merino-suggest = { path = "../merino-suggest" }
futures = "0.3.14"

[dev-dependencies]
pretty_assertions = "0.7.1"
