[package]
name = "merino-adm"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.2.4"
serde = "1.0.125"
serde_derive = "1.0.125"
serde_json = "1.0.64"
serde_qs = "0.8.3"
serde_with = "1.9"
remote-settings-client = { git = "https://github.com/mozilla-services/remote-settings-client", rev = "a489fa2ac9aca128d06eb35dd435f24b7ff9c8f8" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "ab5f2120dc7b3de9384b3f1d5167efb8b3fabcd1"}
anyhow = "1.0.40"
reqwest = { version = "0.11.3", features = ["json"] }
tokio = { version = "1.5.0", features = ["rt", "macros", "rt-multi-thread"] }
radix_trie = "0.2.1"
merino-suggest = { path = "../merino-suggest" }
futures = "0.3.14"
merino-settings = { path = "../merino-settings" }
tracing = "0.1.26"
lazy_static = "1.4.0"
async-trait = "0.1"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.7.1"
actix-rt = "2.2"
