[package]
name = "merino-suggest"
version = "0.1.0"
authors = ["Michael Cooper <mythmon@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
