[package]
name = "merino-suggest"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.2.4"
serde = { version = "1.0.125", features = ["derive"] }
serde_with = "1.9.1"
async-trait = "0.1"
merino-settings = { path = "../merino-settings" }
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"
serde_json = "1.0"
