services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: "local:redis:6379"

  statsd-logger:
    image: catkins/statsd-logger
    ports:
      - "8125:8125/udp"
