[package]
name = "merino-integration-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-rt = "2.2.0"
tokio = "1.5.0"
reqwest = { version = "0.11.3", features = ["json"] }
anyhow = "1.0.40"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
merino-web = { path = "../merino-web" }
merino-settings = { path = "../merino-settings" }
httpmock = "0.5.8"
viaduct = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
