# A fake top-level package for documentation. No code should go here, and most
# documentation should be in the specific packages above.
[package]
name = "merino"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-rt = "2.2.0"
anyhow = "1.0.40"
merino-web = { path = "../merino-web" }
viaduct = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "v75.0.0"}
