[package]
name = "merino-settings"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
config = "0.11.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_with = "1.9"
tracing = "0.1.26"
tracing-subscriber = { version = "0.2.18", features = ["env-filter"] }
serde_path_to_error = "0.1.4"
