debug: false

http:
  listen: "127.0.0.1:8080"
  workers: null

providers:
  adm_rs:
    enabled: false
    storage_path: "./rs-cache"
    collection: "quicksuggest"
  wiki_fruit:
    enabled: false

logging:
  levels: [INFO]
  format: compact

public_documentation: null
