debug: false

http:
  listen: "127.0.0.1:8080"
  workers: null

providers:
  adm_rs:
    enabled: false
    storage_path: "./rs-cache"
    collection: "quicksuggest"
    cache: none
  wiki_fruit:
    enabled: false
    cache: none

redis_cache:
  url: null
  default_ttl_sec: 60

logging:
  levels: [INFO]
  format: compact

public_documentation: null

location:
  maxmind_database: null
