debug: false

http:
  listen: "127.0.0.1:8080"
  workers: null

adm:
  remote_settings:
    storage_path: "./rs-cache"
    collection: "quicksuggest"

logging:
  levels: [INFO]

public_documentation: null
