debug: true
logging:
  format: pretty


providers:
  adm_rs:
    enabled: true
    storage_path: "./rs-cache"
    collection: "quicksuggest"
  wiki_fruit:
    enabled: true

location:
  maxmind_database: "./dev/GeoLite2-City-Test.mmdb"
