[package]
name = "merino-web"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
actix-web = "=4.0.0-beta.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
actix-cors = "0.6.0-beta.1"
tokio = { version = "1.5.0", features = ["sync"] }
tokio-test = "0.4.1"
anyhow = "1.0.40"
merino-suggest = { path = "../merino-suggest" }
merino-adm = { path = "../merino-adm" }
merino-settings = { path = "../merino-settings" }
