[package]
name = "merino-web"
version = "0.1.0"
authors = ["Michael Cooper <mythmon@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "=4.0.0-beta.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
actix-cors = "0.6.0-beta.1"

[dependencies.merino-suggest]
path = "../merino-suggest"
