[package]
name = "merino-web"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "=4.0.0-beta.8"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
actix-cors = "0.6.0-beta.1"
tokio = { version = "1.5.0", features = ["sync"] }
anyhow = "1.0.40"
merino-suggest = { path = "../merino-suggest" }
merino-adm = { path = "../merino-adm" }
merino-cache = { path = "../merino-cache" }
merino-settings = { path = "../merino-settings" }
uuid = { version = "0.8.2", features = ["v4"] }
tracing = { version = "0.1.26", features = ["async-await"] }
tokio-test = "0.4.1"
tracing-actix-web-mozlog = "0.3"
futures-util = "0.3"
tracing-futures = "0.2"
